In [1]:
import torch

In [2]:
# Data una matrice è possibile fare la trasposta con il metodo .T
A = torch.arange(6).reshape((3,2))
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [3]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [4]:
# Matrice simmetrica dunque A == A.T

In [5]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [6]:
A.T

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [7]:
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [8]:
torch.arange(32).reshape((8,2,2))

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]]])

# Proprietà di base per i Tensori

In [9]:
# L'idea è che operatori elementari mantegono la stessa struttura della matrice di partenza

In [10]:
A = torch.arange(6, dtype=torch.float32).reshape(2,3)
B = A.clone()
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

# Reduction
Per sapere la somma degli elementi del tensore e dunque $\sum_{i = 1}^{n} x_i$
è possibile usare la funzione

```
.sum()
```
Lo si può usare anche su matrici di qualsiasi shape().
Nel caso della matrice $A$ che è $m x n$  corrisponde a $\sum_{i = 1}^{m} \sum_{j=1}^{n} a_{ij}$



In [11]:
A.sum()

tensor(15.)

In [12]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [13]:
# Si può sommare anche scegliendo l'asse di riferimento, 0 = colonne , 1 = righe
K = A.sum(axis=0)

In [14]:
A.shape, K.shape

(torch.Size([2, 3]), torch.Size([3]))

In [15]:
R = A.sum(axis=1)
R, R.shape

(tensor([ 3., 12.]), torch.Size([2]))

In [16]:
# Questo produce la somma di tutti gli elementi e di conseguenza uno scalare
A.sum(axis=[0,1]) == A.sum()

tensor(True)

Si possono applicare anche operatori per la media usando **.mean()**
e si può specificare anche l'asse di riferimento con **mean(axis=0)**

In [17]:
A.mean()

tensor(2.5000)

# Non Reduction Sum
Si vuole mantenere la dimensione originaria durante queste operazioni dunque si può specificare attraverso il parametro keepdims

In [18]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [19]:
A.shape

torch.Size([2, 3])

In [20]:
# Facendo la somma si può notare dalla shape che è single-dimension
A.sum(axis = 1), A.sum(axis = 1).shape

(tensor([ 3., 12.]), torch.Size([2]))

In [21]:
# Cosi facendo invece resta una matrice bi-dimension 1 x 3
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [22]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [23]:
# Cumulative Sum
A.cumsum(axis=0)


tensor([[0., 1., 2.],
        [3., 5., 7.]])

# Moltiplicazioni
È una delle operazioni piu importanti. Dati due vettori $ {a},b \in \mathbb{R}^d$ il prodotto è definito come $a^\intercal b=\sum_{i=1}^d a_ib_i$ .
Lo vediamo come 1 x d * d x 1 = 1x1  ovvero uno scalare.



In [24]:
x = torch.ones(3, dtype = torch.float32)
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([1., 1., 1.]), tensor([1., 1., 1.]), tensor(3.))

In [25]:
# si può anche fare nel seguente modo , moltiplicare per poi ottenere la somma
torch.sum(x * y)

tensor(3.)

# Matrix - vector multiplication
Prendiamo una matrice $A$ e lo visualizziamo nella forma
$A= \begin{bmatrix}
a_1^\intercal \\
a_2^\intercal \\
\vdots \\
a_m^\intercal
\end{bmatrix}  $
dove ogni $a_i^\intercal \in \mathbb{R}^n$ e rappresenta l' $i-esimo$ vettore riga della matrice $A$.
Se volessimo moltiplicare per il vettore $x$ allora si ottiene $Ax= \begin{bmatrix}
a_1^\intercal x \\
a_2^\intercal x \\
\vdots \\
a_m^\intercal x
\end{bmatrix} $



In [26]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [27]:
x

tensor([1., 1., 1.])

$Ax= \begin{bmatrix}
0 \ 1 \ 2 \\
3 \ 4 \ 5
\end{bmatrix} \cdot
\begin{bmatrix}
1 \\
1 \\
1
\end{bmatrix} = \begin{bmatrix}
3 \\
12
\end{bmatrix}
$

In [28]:
# Si usa la funzione mv,  Python dispone di un operatore @ che può eseguire sia
# prodotti matrice-vettore che matrice-matrice (a seconda dei suoi argomenti)
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 3., 12.]), tensor([ 3., 12.]))

In [29]:
# Il funzionamento si applica semplicemente anche alle moltiplicazioni di matrici
B = torch.ones(3, 4)
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

# Norme
Informalmente ci dice quanto un vettore sia grande.
Ad esempio la norma $l_2$ misura la *lunghezza euclidea* del vettore.
Siamo interessati al modulo del vettore e non alla dimensionalità in questo caso.
La norma si esprime cosi $\lVert \cdot \rVert$ e mappa il vettore in uno scalare soddisfando 3 proprietà:
- **Scala anche la norma , non solo il vettore moltiplicandolo per uno scalare**
$$\lVert \alpha \mathbf{x} \rVert = | \alpha | \cdot \lVert \mathbf{x} \rVert$$
- **disuguaglianza triangolare**
$$\lVert \mathbf{x} + \mathbf{y} \rVert \leq \lVert \mathbf{x} \rVert + \lVert \mathbf{y} \rVert $$
- **norma sempre positiva** $$\lVert \mathbf{x} \rVert \geq 0 \text{ } \forall \mathbf{x} \neq 0$$

La norma $l_2$ si esprime nel seguente modo:
$$ \lVert \mathbf{x} \rVert_{2} = \sqrt{\sum_{i=1}^n x_i^2} $$

In [30]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

Anche la norma $l_1$ è comune e la misura associata è chiamata **distanza di Manhattan**. Per definizione, la norma somma i valori assoluti degli elementi di un vettore:
$$  \lVert \mathbf{x} \rVert_{1} = \sum_{i=1}^n |x_i| $$
È meno sensibile agli outliers rispetto alla norma $l_2$


In [31]:
torch.abs(u).sum()

tensor(7.)

$l_1$ e $l_2$ sono delle norme specifiche prese dalla formula più generale:
$$\lVert \mathbf{x} \rVert = \left( \sum_{i=1}^{n} |x_i|^p\right)^{1/p} $$

**Frobenius Norms**
Si comporta come la norma $l_2$ per matrici.

$$ \lVert \mathbf{X} \rVert_{F} = \sqrt{\sum_{i=1}^m \sum_{i=1}^n x_{ij}^2} $$