In [1]:
import torch

In [2]:
# con arange si crea un tensore con n numeri da 0 a n - 1
x = torch.arange(12, dtype=torch.float32)

In [3]:
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
# per vedere quanti numeri contiene il tensore si può utilizzare numel()
x.numel()

12

In [5]:
# per vedere la dimensione lungo ogni asse si può usare shape. Come si può notare qui si ha una sola dimensione, quindi è vettore
x.shape

torch.Size([12])

In [6]:
# si può trasformare x in matrice facendo reshape mantenendo sempre il rapporto di 12 elementi
X = x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
x[3] == X[0,3]

tensor(True)

In [10]:
# Se si vuole automaticamente creare la matrice sapendo solo un attributo
# si puo inserire -1 come parametro poiche sappiano n dimensione del tensore vettore
# mentre la forma (h,w) matriciale dato h, w = n/h.
X_2 = x.reshape(-1,4)
X_2

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [11]:
X_2 == X

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [12]:
# Oltre che inzializzare con numeri da 0 a n-1, si può riempire la matrice con 0s o 1s
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
# Oltre che inzializzare con numeri da 0 a n-1, si può riempire la matrice con 0s o 1s
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [14]:
# Oppure inizializzare i dati in maniera randomica come viene utilizzato nei neural networks
torch.randn(3,4)

tensor([[-0.3309,  0.5395, -0.6923,  0.9711],
        [ 1.1716,  0.8130, -0.8749, -0.7623],
        [-0.5873, -1.5249,  1.2579,  1.6024]])

In [15]:
# Si può anche inizializzare un tensore specificando le liste Python
torch.tensor([[2,1,4,3],[1,2,3,4],[5,6,7,8]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [5, 6, 7, 8]])

# Indexing & Slicing

In [17]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [16]:
# Il -1 seleziona l'ultima riga
X[-1]

tensor([ 8.,  9., 10., 11.])

In [20]:
# Seleziona la seconda e terza riga
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [21]:
# Posso accedere al valore specificato dagli indici , 1 = seconda riga, 2 = terza colonna e specificare il valore
X[1,2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [22]:
# Prende la prima e la seconda riga e imposta tutti i valori a 12
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

# Operations

In [23]:
x

tensor([12., 12., 12., 12., 12., 12., 12., 12.,  8.,  9., 10., 11.])

In [24]:
# Posso applicare ad ogni elemento di x l'operatore exp
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [25]:
# Si possono applicare anche i soliti operatori, + - * / **
x = torch.tensor([1.0, 2,4,8])
y = torch.tensor([1,2,2,4])
x + y , x - y, x * y, x / y, x ** y

(tensor([ 2.,  4.,  6., 12.]),
 tensor([0., 0., 2., 4.]),
 tensor([ 1.,  4.,  8., 32.]),
 tensor([1., 1., 2., 2.]),
 tensor([1.0000e+00, 4.0000e+00, 1.6000e+01, 4.0960e+03]))

In [26]:
# In questo modo usando cat si possono concatenare due tensori in uno solo usando dim=0, come righe
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y), dim=0)


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [29]:
# Usando dim = 1 ha aggiunto il tensore Y come colonne
torch.cat((X,Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [30]:
# Somma di tutti gli elementi
X.sum()

tensor(66.)

# Broadcasting
È una procedura che si basa su due step:
  - espandere uno o entrambi gli array copiando gli elementi lungo gli assi con lunghezza 1 in modo tale da avere dopo la trasformazione, due tensori della stessa dimensione
  - Effettuare un operazione elementare sugli array ottenuti

In [32]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [33]:
# Quindi essendo matrici 3 x 1 e 1 x 2 ottengo nuova matrice 3 x 2
a + b


tensor([[0, 1],
        [1, 2],
        [2, 3]])

# Salvare memoria

Questo perche prima Python valuta Y + X e poi assegna un nuovo indirizzo di memoria a Y. Per risolvere bisognerebbe effetuare operazioni che fanno aggiornamenti *in place*.

In [34]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [37]:
Y.shape

torch.Size([3, 4])

In [36]:
# Esempio
# Creo un nuovo tensore delle stesse dimensioni di Y ma riempito di zero
Z = torch.zeros_like(Y)
Z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
# L'operatore [:] ci consente di effettuare operazioni in place , come si può vedere dall'indirizzo ID dell'oggetto Z
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 133610572810576
id(Z): 133610572810576


In [39]:
# Se X ad esempio non viene riusato nelle operazioni successive, posso usare X[:] = X + Y o  X += Y per
# ridurre la memory overhead dell'operazione
before = id(X)
X += Y
id(X) == before

True

# Conversioni in altri Python Objects

In [41]:
A = X.numpy()

In [42]:
A

array([[ 2.,  3.,  8.,  9.],
       [ 9., 12., 15., 18.],
       [20., 21., 22., 23.]], dtype=float32)

In [43]:
type(A)

numpy.ndarray

In [45]:
B = torch.from_numpy(A)
B,type(B)

(tensor([[ 2.,  3.,  8.,  9.],
         [ 9., 12., 15., 18.],
         [20., 21., 22., 23.]]),
 torch.Tensor)

In [46]:
# Si può convertire un tensore size-1 in uno scalare usando la funzione item
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [48]:
X,Y

(tensor([[ 2.,  3.,  8.,  9.],
         [ 9., 12., 15., 18.],
         [20., 21., 22., 23.]]),
 tensor([[ 2.,  2.,  6.,  6.],
         [ 5.,  7.,  9., 11.],
         [12., 12., 12., 12.]]))

# Esercizi

In [47]:
X < Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [50]:
 P = X > Y

In [51]:
P

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [73]:
q = torch.arange( 6, dtype =torch.float32).reshape((6, 1))
w = torch.arange( 3).reshape((1, 3))
q,w

(tensor([[0.],
         [1.],
         [2.],
         [3.],
         [4.],
         [5.]]),
 tensor([[0, 1, 2]]))

In [74]:
q +w

tensor([[0., 1., 2.],
        [1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.],
        [4., 5., 6.],
        [5., 6., 7.]])

# Data Preprocessing

In [85]:
# Creazione di un dataset con file CSV
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

In [86]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000


In [88]:
# Siccome vogliamo lavorare con un supervised learning abbiamo bisogno di fare data cleaning
# Si può procedere via imputation o deletion.
# Imputation = stimare i dati che sono NaN
# Deletion = cancello i valori NaN

# Esempio di Imputation in Pandas
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs

NumRooms RoofType
0       NaN      NaN
1       2.0      NaN
2       4.0    Slate
3       NaN      NaN

In [89]:
targets

0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64

In [90]:
# Qui converte i RoofType column in RoofType_Slate e RoofType_nan e assegna True o False
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True


In [91]:
# Per i valori numerici mancanti si può usare fill na con la media dell'input
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True


In [92]:
import torch

# Si possono adesso convertire gli inputs e targets in tensori visto che sono numerical
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
X,y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))